name:
on: [push, pull_request, create, delete, issue_comment]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: ./.github/*,.git,./package.json,./package-lock.json,./node_modules,./tests,./config,*.png,Dockerfile,./scripts,*.spec.js,./plugins/azure/storageaccounts/storageAccountsAADEnabled.js,./plugins/aws/cloudtrail/cloudtrailBucketAccessLogging.js,./helpers/google/index.js,*zip
          ignore_words_list: iam,\"tRe\",AKS,aks,optin,callInt,callInt
      - run: npm install

      - name: Lint
        run: npm run lint

      - name: NPM Test
        run: npm test
      - name: Upload Coverage Reports to GitHub
        id: upload-coverage-github
        uses: actions/upload-artifact@v4
        with:
          path: bazel-out/_coverage
          name: "coverage"
  upload-coverage-to-backstage:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    permissions:
      id-token: write
    uses: rtkwlf-actions/common-build/.github/workflows/code-coverage-upload.yaml@v8
    with:
      artifact-name: "coverage"
      component-name: "${{ github.repository_owner }}-${{ github.event.repository.name }}"
